# Generated by Django 3.2.9 on 2021-12-20 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequirementsDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('deadline', models.DateField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_budget', models.BigIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('quantity', models.IntegerField()),
                ('units', models.CharField(max_length=20)),
                ('industry_category', models.CharField(choices=[('CT', 'Clothing and Textiles'), ('PCP', 'Petroleum, Chemicals and Plastics'), ('ECT', 'Electronics, Computers and Transportation'), ('FP', 'Food Production'), ('MM', 'Metal Manufacturing'), ('WLP', 'Wood, Leather and Paper')], max_length=3)),
                ('req_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request_quote.requirementsdoc')),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.BigIntegerField()),
                ('delivery_by', models.DateField()),
                ('quantity_provided', models.IntegerField()),
                ('units', models.CharField(max_length=20)),
                ('message', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('updated_at', models.DateField(auto_now=True, null=True)),
                ('selected', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request_quote.item')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.vendor')),
            ],
            options={
                'unique_together': {('item', 'owner')},
            },
        ),
    ]
