# Generated by Django 4.0 on 2021-12-18 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.BigIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('quantity', models.IntegerField()),
                ('units', models.CharField(max_length=20)),
                ('industry_category', models.CharField(choices=[('CT', 'Clothing and Textiles'), ('PCP', 'Petroleum, Chemicals and Plastics'), ('ECT', 'Electronics, Computers and Transportation'), ('FP', 'Food Production'), ('MM', 'Metal Manufacturing'), ('WLP', 'Wood, Leather and Paper')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='RequirementsDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deadline', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.BigIntegerField()),
                ('delivery_by', models.DateTimeField()),
                ('quantity_provided', models.IntegerField()),
                ('units', models.CharField(max_length=20)),
                ('message', models.CharField(blank=True, max_length=200, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request_quote.item')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='req_doc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request_quote.requirementsdoc'),
        ),
    ]
