# Generated by Django 3.2.9 on 2021-12-20 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request_quote', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='selected',
        ),
    ]
