# Generated by Django 3.2.9 on 2021-12-20 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_quote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='delivery_by',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='quote',
            name='updated_at',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
