# Generated by Django 4.0 on 2021-12-18 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request_quote', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='price',
            new_name='max_budget',
        ),
    ]
