# Generated by Django 3.2.9 on 2021-12-20 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '__first__'),
        ('request_quote', '0002_auto_20211220_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request_quote.item'),
        ),
        migrations.AlterUniqueTogether(
            name='quote',
            unique_together={('item', 'owner')},
        ),
    ]
