# Generated by Django 3.2.9 on 2021-12-20 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_quote', '0002_remove_quote_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
