# Generated by Django 3.2.9 on 2021-12-19 19:59

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_vendor_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='phone_no',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
